# Site settings
title: Aman Chopra # site title
description: >- # site description
  Welcome to my site!
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/img/avatar.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/Aman-Chopra/aman-chopra.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Aman Chopra # author name
  bio: >- # tell to the world
    Hello! I am Aman Chopra. I am currently pursuing my Master's in Computer Science from the Courant Institute
    of Mathematical Sciences - New York University. I have completed my Bachelor's in Technology from the Manipal Institue of Technology,
    Manipal, India. Post that, I have worked as a Senior Software Engineer at Samsung Semiconductor India Research and Development.
    I am an enthusiastic programmer with a keen interest and expertise in ML, NLP, Application and Web Development.
  username: user # general username
  github: Aman-Chopra # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: ac8511@nyu.edu # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://klise.now.sh" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true  

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
